package ie.deloitte.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Sampleentry service. Represents a row in the &quot;Sampleentry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ie.deloitte.sample.model.impl.SampleentryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ie.deloitte.sample.model.impl.SampleentryImpl}.
 * </p>
 *
 * @author JY
 * @see Sampleentry
 * @see ie.deloitte.sample.model.impl.SampleentryImpl
 * @see ie.deloitte.sample.model.impl.SampleentryModelImpl
 * @generated
 */
public interface SampleentryModel extends BaseModel<Sampleentry>,
    StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a sampleentry model instance should use the {@link Sampleentry} interface instead.
     */

    /**
     * Returns the primary key of this sampleentry.
     *
     * @return the primary key of this sampleentry
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this sampleentry.
     *
     * @param primaryKey the primary key of this sampleentry
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this sampleentry.
     *
     * @return the uuid of this sampleentry
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this sampleentry.
     *
     * @param uuid the uuid of this sampleentry
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the entry ID of this sampleentry.
     *
     * @return the entry ID of this sampleentry
     */
    public long getEntryId();

    /**
     * Sets the entry ID of this sampleentry.
     *
     * @param entryId the entry ID of this sampleentry
     */
    public void setEntryId(long entryId);

    /**
     * Returns the group ID of this sampleentry.
     *
     * @return the group ID of this sampleentry
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this sampleentry.
     *
     * @param groupId the group ID of this sampleentry
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this sampleentry.
     *
     * @return the company ID of this sampleentry
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this sampleentry.
     *
     * @param companyId the company ID of this sampleentry
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this sampleentry.
     *
     * @return the user ID of this sampleentry
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this sampleentry.
     *
     * @param userId the user ID of this sampleentry
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this sampleentry.
     *
     * @return the user uuid of this sampleentry
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this sampleentry.
     *
     * @param userUuid the user uuid of this sampleentry
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this sampleentry.
     *
     * @return the user name of this sampleentry
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this sampleentry.
     *
     * @param userName the user name of this sampleentry
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this sampleentry.
     *
     * @return the create date of this sampleentry
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this sampleentry.
     *
     * @param createDate the create date of this sampleentry
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this sampleentry.
     *
     * @return the modified date of this sampleentry
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this sampleentry.
     *
     * @param modifiedDate the modified date of this sampleentry
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this sampleentry.
     *
     * @return the name of this sampleentry
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this sampleentry.
     *
     * @param name the name of this sampleentry
     */
    public void setName(String name);

    /**
     * Returns the message of this sampleentry.
     *
     * @return the message of this sampleentry
     */
    @AutoEscape
    public String getMessage();

    /**
     * Sets the message of this sampleentry.
     *
     * @param message the message of this sampleentry
     */
    public void setMessage(String message);

    /**
     * Returns the email of this sampleentry.
     *
     * @return the email of this sampleentry
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this sampleentry.
     *
     * @param email the email of this sampleentry
     */
    public void setEmail(String email);

    /**
     * Returns the guestbook ID of this sampleentry.
     *
     * @return the guestbook ID of this sampleentry
     */
    public long getGuestbookId();

    /**
     * Sets the guestbook ID of this sampleentry.
     *
     * @param guestbookId the guestbook ID of this sampleentry
     */
    public void setGuestbookId(long guestbookId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ie.deloitte.sample.model.Sampleentry sampleentry);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ie.deloitte.sample.model.Sampleentry> toCacheModel();

    @Override
    public ie.deloitte.sample.model.Sampleentry toEscapedModel();

    @Override
    public ie.deloitte.sample.model.Sampleentry toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
