package ie.deloitte.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Samplebook service. Represents a row in the &quot;Samplebook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ie.deloitte.sample.model.impl.SamplebookModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ie.deloitte.sample.model.impl.SamplebookImpl}.
 * </p>
 *
 * @author JY
 * @see Samplebook
 * @see ie.deloitte.sample.model.impl.SamplebookImpl
 * @see ie.deloitte.sample.model.impl.SamplebookModelImpl
 * @generated
 */
public interface SamplebookModel extends BaseModel<Samplebook>,
    StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a samplebook model instance should use the {@link Samplebook} interface instead.
     */

    /**
     * Returns the primary key of this samplebook.
     *
     * @return the primary key of this samplebook
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this samplebook.
     *
     * @param primaryKey the primary key of this samplebook
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this samplebook.
     *
     * @return the uuid of this samplebook
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this samplebook.
     *
     * @param uuid the uuid of this samplebook
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the guestbook ID of this samplebook.
     *
     * @return the guestbook ID of this samplebook
     */
    public long getGuestbookId();

    /**
     * Sets the guestbook ID of this samplebook.
     *
     * @param guestbookId the guestbook ID of this samplebook
     */
    public void setGuestbookId(long guestbookId);

    /**
     * Returns the group ID of this samplebook.
     *
     * @return the group ID of this samplebook
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this samplebook.
     *
     * @param groupId the group ID of this samplebook
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this samplebook.
     *
     * @return the company ID of this samplebook
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this samplebook.
     *
     * @param companyId the company ID of this samplebook
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this samplebook.
     *
     * @return the user ID of this samplebook
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this samplebook.
     *
     * @param userId the user ID of this samplebook
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this samplebook.
     *
     * @return the user uuid of this samplebook
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this samplebook.
     *
     * @param userUuid the user uuid of this samplebook
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this samplebook.
     *
     * @return the user name of this samplebook
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this samplebook.
     *
     * @param userName the user name of this samplebook
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this samplebook.
     *
     * @return the create date of this samplebook
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this samplebook.
     *
     * @param createDate the create date of this samplebook
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this samplebook.
     *
     * @return the modified date of this samplebook
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this samplebook.
     *
     * @param modifiedDate the modified date of this samplebook
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this samplebook.
     *
     * @return the name of this samplebook
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this samplebook.
     *
     * @param name the name of this samplebook
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ie.deloitte.sample.model.Samplebook samplebook);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ie.deloitte.sample.model.Samplebook> toCacheModel();

    @Override
    public ie.deloitte.sample.model.Samplebook toEscapedModel();

    @Override
    public ie.deloitte.sample.model.Samplebook toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
