package ie.deloitte.sample.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ie.deloitte.sample.model.Sampleentry;
import ie.deloitte.sample.service.SampleentryLocalServiceUtil;

/**
 * The extended model base implementation for the Sampleentry service. Represents a row in the &quot;Sampleentry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SampleentryImpl}.
 * </p>
 *
 * @author JY
 * @see SampleentryImpl
 * @see ie.deloitte.sample.model.Sampleentry
 * @generated
 */
public abstract class SampleentryBaseImpl extends SampleentryModelImpl
    implements Sampleentry {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a sampleentry model instance should use the {@link Sampleentry} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SampleentryLocalServiceUtil.addSampleentry(this);
        } else {
            SampleentryLocalServiceUtil.updateSampleentry(this);
        }
    }
}
