package ie.deloitte.sample.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ie.deloitte.sample.model.Samplebook;
import ie.deloitte.sample.service.SamplebookLocalServiceUtil;

/**
 * The extended model base implementation for the Samplebook service. Represents a row in the &quot;Samplebook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SamplebookImpl}.
 * </p>
 *
 * @author JY
 * @see SamplebookImpl
 * @see ie.deloitte.sample.model.Samplebook
 * @generated
 */
public abstract class SamplebookBaseImpl extends SamplebookModelImpl
    implements Samplebook {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a samplebook model instance should use the {@link Samplebook} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SamplebookLocalServiceUtil.addSamplebook(this);
        } else {
            SamplebookLocalServiceUtil.updateSamplebook(this);
        }
    }
}
